language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: swoeste-github
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -DskipTests
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
